security.basic.enable: false
security.ignored: /**
security.enable-csrf: false
logging:
  level:
    org.springframework.security.web: DEBUG

spring:
  application:
    name: app
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: deepseek-r1:1.5b
          temperature: 0.0
    chat:
      client:
        enabled: false
#        embedding:
#          enabled: false
#    chat:
#      options:
#        model: gpt

application:
  name: Inspectia
  security:
    jwt:

      secret-key: ${JWT_SECRET_KEY}
      expiration: ${JWT_TOKEN_EXPIRATION}
      refresh-token:
        expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}
firebase:
  database:
    service-account-path: ${FIREBASE_SERVICE_ACCOUNT_KEY}
    name: Inspectia-Db
    region: us-central1
