security.basic.enable: false
security.ignored: /**
security.enable-csrf: false
logging:
  level:
    org.springframework.security.web: DEBUG

spring:
  application:
    name: app

application:
  name: Inspectia
  security:
    jwt:

      secret-key: ${JWT_SECRET_KEY}
      expiration: ${JWT_TOKEN_EXPIRATION}
      refresh-token:
        expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}
firebase:
  database:
    service-account-path: ${FIREBASE_SERVICE_ACCOUNT_KEY}
    name: Inspectia-Db
    region: us-central1
